// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.3.0
// source: ip2adder.proto

package service

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IpInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip []string `protobuf:"bytes,1,rep,name=ip,proto3" json:"ip,omitempty"`
}

func (x *IpInfo) Reset() {
	*x = IpInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip2adder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpInfo) ProtoMessage() {}

func (x *IpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ip2adder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpInfo.ProtoReflect.Descriptor instead.
func (*IpInfo) Descriptor() ([]byte, []int) {
	return file_ip2adder_proto_rawDescGZIP(), []int{0}
}

func (x *IpInfo) GetIp() []string {
	if x != nil {
		return x.Ip
	}
	return nil
}

type AdderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adder []string `protobuf:"bytes,1,rep,name=adder,proto3" json:"adder,omitempty"`
}

func (x *AdderInfo) Reset() {
	*x = AdderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ip2adder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdderInfo) ProtoMessage() {}

func (x *AdderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ip2adder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdderInfo.ProtoReflect.Descriptor instead.
func (*AdderInfo) Descriptor() ([]byte, []int) {
	return file_ip2adder_proto_rawDescGZIP(), []int{1}
}

func (x *AdderInfo) GetAdder() []string {
	if x != nil {
		return x.Adder
	}
	return nil
}

var File_ip2adder_proto protoreflect.FileDescriptor

var file_ip2adder_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x69, 0x70, 0x32, 0x61, 0x64, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x18, 0x0a, 0x06, 0x49, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x22, 0x21, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x61, 0x64, 0x64, 0x65, 0x72, 0x32, 0x46, 0x0a, 0x0f, 0x49, 0x70, 0x32, 0x41, 0x64, 0x64,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x65, 0x72, 0x54, 0x6f, 0x49, 0x70, 0x12, 0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x49, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x12, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ip2adder_proto_rawDescOnce sync.Once
	file_ip2adder_proto_rawDescData = file_ip2adder_proto_rawDesc
)

func file_ip2adder_proto_rawDescGZIP() []byte {
	file_ip2adder_proto_rawDescOnce.Do(func() {
		file_ip2adder_proto_rawDescData = protoimpl.X.CompressGZIP(file_ip2adder_proto_rawDescData)
	})
	return file_ip2adder_proto_rawDescData
}

var file_ip2adder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ip2adder_proto_goTypes = []interface{}{
	(*IpInfo)(nil),    // 0: message.IpInfo
	(*AdderInfo)(nil), // 1: message.AdderInfo
}
var file_ip2adder_proto_depIdxs = []int32{
	0, // 0: message.Ip2AdderService.GetAdderToIp:input_type -> message.IpInfo
	1, // 1: message.Ip2AdderService.GetAdderToIp:output_type -> message.AdderInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ip2adder_proto_init() }
func file_ip2adder_proto_init() {
	if File_ip2adder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ip2adder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ip2adder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ip2adder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ip2adder_proto_goTypes,
		DependencyIndexes: file_ip2adder_proto_depIdxs,
		MessageInfos:      file_ip2adder_proto_msgTypes,
	}.Build()
	File_ip2adder_proto = out.File
	file_ip2adder_proto_rawDesc = nil
	file_ip2adder_proto_goTypes = nil
	file_ip2adder_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// Ip2AdderServiceClient is the client API for Ip2AdderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Ip2AdderServiceClient interface {
	GetAdderToIp(ctx context.Context, in *IpInfo, opts ...grpc.CallOption) (*AdderInfo, error)
}

type ip2AdderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIp2AdderServiceClient(cc grpc.ClientConnInterface) Ip2AdderServiceClient {
	return &ip2AdderServiceClient{cc}
}

func (c *ip2AdderServiceClient) GetAdderToIp(ctx context.Context, in *IpInfo, opts ...grpc.CallOption) (*AdderInfo, error) {
	out := new(AdderInfo)
	err := c.cc.Invoke(ctx, "/message.Ip2AdderService/GetAdderToIp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Ip2AdderServiceServer is the server API for Ip2AdderService service.
type Ip2AdderServiceServer interface {
	GetAdderToIp(context.Context, *IpInfo) (*AdderInfo, error)
}

// UnimplementedIp2AdderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIp2AdderServiceServer struct {
}

func (*UnimplementedIp2AdderServiceServer) GetAdderToIp(context.Context, *IpInfo) (*AdderInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdderToIp not implemented")
}

func RegisterIp2AdderServiceServer(s *grpc.Server, srv Ip2AdderServiceServer) {
	s.RegisterService(&_Ip2AdderService_serviceDesc, srv)
}

func _Ip2AdderService_GetAdderToIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Ip2AdderServiceServer).GetAdderToIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Ip2AdderService/GetAdderToIp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Ip2AdderServiceServer).GetAdderToIp(ctx, req.(*IpInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ip2AdderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Ip2AdderService",
	HandlerType: (*Ip2AdderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdderToIp",
			Handler:    _Ip2AdderService_GetAdderToIp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ip2adder.proto",
}
